---
- name: Get API Gateway logs
  command: >
    aws logs filter-log-events
    --log-group-name "API-Gateway-Execution-Logs_{{ api_gateway_id }}/stages/prod"
    --region {{ aws_region }}
    --start-time {{ (ansible_date_time.epoch | int - (retention_hours * 3600)) * 1000 }}
    --filter-pattern "ERROR"
  register: api_gateway_logs
  changed_when: false

- name: Get Lambda logs
  command: >
    aws logs filter-log-events
    --log-group-name "/aws/lambda/{{ lambda_name }}"
    --region {{ aws_region }}
    --start-time {{ (ansible_date_time.epoch | int - (retention_hours * 3600)) * 1000 }}
    --filter-pattern "ERROR"
  register: lambda_logs
  changed_when: false
