---
- name: Extract URL components
  include_tasks: extract_url.yml

- name: Resolve API Gateway ID
  include_tasks: resolve_api_gateway.yml

- name: Fetch logs
  include_tasks: fetch_logs.yml

- name: Show investigation results
  debug:
    msg: "{{ investigation_report }}"

